# Generated by Django 3.0.11 on 2021-01-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0005_cardspage_tourpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardspage',
            name='cards',
            field=models.ManyToManyField(blank=True, help_text='Select a page to create card', related_name='page_cards', to='wagtailcore.Page'),
        ),
    ]
