# Generated by Django 3.0.11 on 2021-01-24 22:55

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0006_auto_20210124_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardspage',
            name='cards',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select a page to create card', related_name='page_cards', to='wagtailcore.Page'),
        ),
    ]
