# Generated by Django 3.0.11 on 2021-01-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_body'),
        ('home', '0007_auto_20210124_2255'),
    ]

    operations = [
    ]
