# Generated by Django 3.0.11 on 2021-03-01 20:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210301_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
